### ISSUE TITLE
Revisit user stories

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#16]

**Comment by jona937d** [comment]
## User stories



![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/92019351/c12d8dab-64af-4967-8ccf-c62a89b08ae4)




![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/92019351/e4ec07d2-5f3d-4039-9cad-33f03fd69197)
