### ISSUE TITLE
Setup SupaBase

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#17]

**Comment by jona937d** [comment]
Projektdatabase
Navn: NyVogn
Kode: !NyVogn123!

**Comment by jona937d** [comment]
## Supabase database

![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/92019351/15aad3cc-1bcc-4d16-9bb0-a748075d34f6)
