### ISSUE TITLE
Create Plan for User-testing

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#21]

**Comment by EmilBystrup** [comment]
Test different landing page questions.
* Budget (Price range) 
* Power Source
* Type 
* Usage

**Comment by EmilBystrup** [comment]
See LOFA #29 for potential questions to ask the end consumer

**Comment by jona937d** [comment]
QA/ user test


using the Five-act interview method
 

**Act 1: Friendly Welcome** 

Thank you for participating in our user-test of a prototype of our car-recommendation tool, NyVogn. 

- What's your name? 

- How old are you? 

- Where are you from? 

- From a scale of 1-10 how much interest do you have in cars? 

**Act 2: Context Questions** 

- Have you ever bought a brand-new car (if, how many)? 

- How many dealerships did you visit before finalizing the deal? 

- If you were to buy a brand-new car how many hours of research would you do? 

- What do you research? (Price, look, specs, type...) 

- Do you have a brand-loyalty, or are you open to buy a car from any brand?  

- What´s your estimated budget for buying a new car? 

**Act 3: Introducing the Prototype** 

Imagine a system where you share your specific car preferences with us. We take this information and apply our special algorithm to create a personalized list of brand-new cars that perfectly match your requirements. We consider everything, from the type of car you want to its size and the budget you have in mind. Our algorithm then compares your preferences with the extensive database of available cars to find the ideal match that suits you best. 

**Act 4: Tasks** 

- Browse all the cars 

- Find the car that suits you the best 

- Find the nearest dealer to you 

- Visit the dealers site 

_more tasks coming as the webpage is being developed_

**Act 5: Quick Debrief** 

- What worked out great? 

- What didn’t work out great? 


@lakruzz what do you think?

**Comment by lakruzz** [comment]
Hmmm - Are you planning on asking these questions to user (a kind of market analysis) or are you planing to release a website where some of these questions (which?) are assumptions you want to test?

Not sure I fully understand your QA/user test? (QA = Quality Assurance, the concept seems a bit off in this stage of development)

I general - it sounds like you are asking for opinions - But your quest is for a market fit; You should only trust **YODA**; Your Own DAta. So what can you build, that allows you to elicit data, so yu can measure, and then based on that either confirm or affirm you hypothesis?

**Comment by jona937d** [comment]
Yes, clearly we have made misconceptions regarding the term "QA-testing", because the above outline of an interview has nothing to do with QA-testing. That is purely user-testing/interview. We will reconsider and make a seperate QA-test plan. 

Thanks for the swift and lengthy response and sorry for the confusion :) .

**Comment by jona937d** [comment]
## Five-act interview 

 

### Act 1: Friendly Welcome  

Thank you for participating in our user-test of a prototype of our car-recommendation tool, NyVogn. 

What's your name? 

How old are you? 

Where are you from? 

From a scale of 1-10 how much interest do you have in cars? 

### Act 2: Context Questions 

Have you ever bought a brand-new car (if, how many)? 

What did the process look like before you bought it? 

How did you obtain information about what car to get? 

How many dealerships did you visit before finalizing the deal? 

If you were to buy a brand-new car how many hours of research would you do? 

What do you research? (Price, look, specs, type...)  

Do you have a brand-loyalty, or are you open to buy a car from any brand?  

Would you trust a webpage to recommend a car, based on your preferences? 

What conditions would need to be met for you to enhance your trust? 

Would you visit a dealership, based on the recommendation the webpage gives you?  

What´s your estimated budget for buying a new car? 

### Act 3: Introducing the Prototype 

Imagine a system where you share your specific car preferences with us. We take this information and apply our special algorithm to create a personalized list of brand-new cars that perfectly match your requirements. We consider everything, from the type of car you want to its size and the budget you have in mind. Our algorithm then compares your preferences with the extensive database of available cars to find the ideal match that suits you best. 

### Act 4: Tasks 

Find the car that suits you the best. 

Browse the car catalog. 

What is the price of the SQ5 in the “sport SUV”-section? 

How much horsepower does it have? 

Find the nearest dealer to you. 

Visit the dealers site. 

### Act 5: Quick Debrief 

What worked out great? 

What didn’t work out great?

**Comment by jona937d** [comment]
## Person 1 

### Act 1 

Name: Jens 

Age: 29 

Where are you from: Virum 

From a scale of 1-10 how much interest do you have in cars: 3 

### Act 2 

Have you ever bought a brand-new car (if, how many)? 
No 

What did the process look like before you bought it? 

How did you obtain information about what car to get? 

How many dealerships did you visit before finalizing the deal? 

If you were to buy a brand-new car how many hours of research would you do? 
Maybe 2-3 hours 

What do you research? (Price, look, specs, type...)  
Price and specifications 

Do you have a brand-loyalty, or are you open to buy a car from any brand?  
Any brand 

Would you trust a webpage to recommend a car, based on your preferences? 
Yes 

What conditions would need to be met for you to enhance your trust? 
Correct info displayed 

Would you visit a dealership, based on the recommendation the webpage gives you? 
Yes  

What´s your estimated budget for buying a new car? 
250.000 

### Act 4 

Browse the car catalog.  
Done 

What is the price of the SQ5 in the “sport SUV”-section? 
Took about 3 mins to find the specific car model. 

How much horsepower does it have? 
Done 

Find the nearest dealer to you. 
Done 

Visit the dealers site. 
Done 

### Act 5 

Confusing at first. Big difference between Figma and website. The idea is good, never heard about it before.  

## Person 2 

### Act 1 

Name: Thomas 

Age: 29 

Where are you from: Holte 

From a scale of 1-10 how much interest do you have in cars: 5 

### Act 2 

Have you ever bought a brand-new car (if, how many)? 
No 

What did the process look like before you bought it? 

How did you obtain information about what car to get? 

How many dealerships did you visit before finalizing the deal? 

If you were to buy a brand-new car how many hours of research would you do? 
A few hours 

What do you research? (Price, look, specs, type...)  
Price and specifications 

Do you have a brand-loyalty, or are you open to buy a car from any brand?  
Any brand 

Would you trust a webpage to recommend a car, based on your preferences? 
Yes if the information such as price and specifications is correct 

What conditions would need to be met for you to enhance your trust? 
Good UX, good reviews  

Would you visit a dealership, based on the recommendation the webpage gives you? 
Yes  

What´s your estimated budget for buying a new car? 
400.000 

### Act 4 

Browse the car catalog.  
Done 

What is the price of the SQ5 in the “sport SUV”-section? 
Done, person had a hard time scrolling through the catalog and finding the correct model. 

How much horsepower does it have? 
Done 

Find the nearest dealer to you. 
Done 

Visit the dealers site. 
Done 

### Act 5 

Good idea, always assumed the website like Bilbasen had something similar (as in, an expectation of something similar already existed).  

## Person 3 

### Act 1: 

Name: Anders 

Age: 53 

From: Høng (Kalundborg kommune) 

Interest in cars from 1-10: 6 


### Act 2: 

Have you ever bought a brand-new car (if, how many)?  

Yes 2 

What did the process look like before you bought it?  

Internet research, dealership visit, test drive, talks with bank, order. 

How did you obtain information about what car to get?  

Internet research, dealership visits, friends, colleagues. 

How many dealerships did you visit before finalizing the deal? 

5-6 

If you were to buy a brand-new car how many hours of research would you do? 

40+ hours 

What do you research? (Price, look, specs, type...)   

Price, Green tax, Maintenance, Range, Looks, Equipment,  

Do you have a brand-loyalty, or are you open to buy a car from any brand?  

Everything other than American ICE´s 

Would you trust a webpage to recommend a car, based on your preferences?  

Yes if it has brands I know 

What conditions would need to be met for you to enhance your trust? 

If every car brand is represented and none of them pays to have their cars represented over others 

Would you visit a dealership, based on the recommendation the webpage gives you?  

Yes, if they are within 50km, so I can get my car serviced. 

What´s your estimated budget for buying a new car?  

450k dkk max
