### ISSUE TITLE
Revisit Features

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#23]
Update the features, add new features etc.

**Comment by jona937d** [comment]
MVP (Minimum Viable Product): 

- User Profile Creation: We'll start by allowing our users to create personalized profiles, ensuring they get recommendations tailored to their preferences. 

- Car Database: Our core database of car models will be in place, providing comprehensive information about available cars. 

- Recommendation Engine: We'll develop the heart of our product, the recommendation engine, which will give our users basic recommendations. 

- Car detail page: We want the users to be able to see relevant details (specs, price CO2 emissions etc.) about the cars that they are recommended or if they are simply browsing the catalog. 

- Local Dealership Locator: To encourage immediate action on recommendations, we'll include a feature that helps users find nearby dealerships. 

Near Future: 

- Filter and Sorting Options: In the near future, we'll add features that allow users to narrow down their choices easily. 

- Notifications: To keep our users engaged and informed, we'll introduce push notifications and email alerts. 

- Chat Support: We'll provide a chat support feature to assist users and offer real-time guidance. 

- Privacy Controls: We'll prioritize user data security by implementing robust privacy controls and options. 

- Feedback and Improvement System: Feedback from users will be essential. So, we'll establish a system for users to share their thoughts and help us improve. 

- User Reviews and Ratings: Building trust is crucial. So, we'll ensure users can read and leave reviews and ratings for both cars and dealerships. (Add to favorite / Save) 

Far Future: 

- Virtual Test Drives: Down the road, we plan to offer a unique and immersive experience with virtual test drives. 

- Comparison Tool: Enhancing user decision-making will be our focus in the far future. 

- Price Alerts: We'll consider adding price tracking and alert features as our platform gains traction. 

- User Community: Building a strong user community is important, and we'll introduce forums and discussion boards when we have a larger user base. 

- Mobile App: Expanding accessibility with a mobile app will be on our agenda once our web platform is well-established. 

- Analytics Dashboard: As we grow, an analytics dashboard for dealerships to track leads will become more relevant. 

- International Support: Expanding internationally will be part of our long-term growth strategy. 

- Car Financing Calculator: We'll consider adding this useful tool to help users estimate monthly payments. 

- Video Content: To enhance the user experience, we'll explore adding video reviews and walkthroughs. 

- Integration with social media: Encouraging word-of-mouth referrals will be crucial, and we'll optimize our integration with social media platforms as we grow.
