### ISSUE TITLE
Create Team explaination

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#30]
Go into depth with how we work as a team and why we will be able to acomplish our goals with this team

**Comment by EmilBystrup** [comment]
Even though most of us in the group are Business & IT students, with the exception of Zaisa, who is pursuing multimedia design, our group dynamic operates seamlessly. We bring diverse academic interests and goals to the table, and it's this very diversity that strengthens our collaboration.

The vast and multifaceted domain of Business & IT studies has equipped us with a wide array of methods and tools. When we harness these collective skills and knowledge, we have at our disposal the comprehensive toolkit necessary to develop a fully realized and successful digital product. With the addition of Zaisa, we believe that our team is perfect for this project.

Thankfully, we are all very adaptable. So, if something arises for which we don't have a solution, we possess the capabilities to resolve it. As a team of seven, we can also assign one or two team members to embark on a learning journey to address the issue, whether it involves a system, program, or any other challenge. In essence, should any unresolved issues arise, we are committed to acquiring the necessary skills and competencies.

This is our team and roles: 
Emil Schirmer Lenschau - Business Analyst & Organizer 
Magnus Christophersen – Programmer & Implementor
Mathias Villa Fonseca – Strategist & Conceptualiser
Jonas Hvid Nielsen - UX/QA, Conceptualiser, Technical stuff.
Lucas Molnar Jonasen - Quality assurance & Organizer 
Haidar Ansari - Technical stuff, Product development, Business Analyst
Zasia Meincke - Frontend, UX Design and research, So-Me marketing

**Comment by jona937d** [comment]
![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/92019351/2a5db4f0-c549-4120-84d3-6b52ff315d15)
