### ISSUE TITLE
Brainstorm names for the platform

### ISSUE THREAD

**Issue by haidaransari** [kea-dpd/Group-Car-Recommendation#32]

**Comment by EmilBystrup** [comment]
CarCompass (Exists) 

MotorMentor (Exists) 

MotorMatch (Organisk) (Motor Match exists) 

AutoNavigator (Danish site - Auto Navigatør) 

CarCurator (Exists) 

DriveDiscover (Drive and Discover) 

WheelWise (Exists) 

AutoInsight (Exists) 

A Car Match (Danish site - CarMatch) 

Wagon 

Cruisefit 

Wagonfit 

Findmigenbil.dk 

Carvoe 

Carfit 

Bilfit.dk 

Nybil.dk 

Mujaffasbmw.dk 

CarOps.com 

CarDrip 

Autofit 

NySlæde.dk 

Winner = Nyvogn.dk
