### ISSUE TITLE
Create Logos for "NyVogn"

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#45]

**Comment by zmeincke** [comment]
![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/112558241/73330dd9-0521-4ec0-8a0c-c86306b0b9cb)

**Comment by zmeincke** [comment]
![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/112558241/cc288bfc-6357-438b-aaad-a1aedbcf605a)
