### ISSUE TITLE
Onboarding, structure, project etc

### ISSUE THREAD

**Issue by lakruzz** [kea-dpd/Group-Car-Recommendation#49]
Hi team 

Do you have a place where you share files of various kinds? Can you pls make sure I have access to it too.

Maybe you have something like an onboarding document? It's typically the purpose of the `README.md` file in the root of the directory. but when I read your README file it didn't give me any clues. Maybe it's not updated yet? or you have the information elsewhere?

Can you provide me with a short instruction on how to read your project here on GitHub and where to find the source (files) you work on?

**Comment by lakruzz** [comment]
Hi @kea-dpd/group-car-recommendation 

I have this issue marked

![image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/155492/1aa6b0b0-046d-4157-b269-ef5fcc802b0d)

Did you see this issue? It's closed - but not worked on or replied 🤷‍♂️

**Comment by luca2422** [comment]
@lakruzz Sorry for the late reply. We have updated our Readme file to show where you have access to our shared files.

**Comment by lakruzz** [comment]
It looks good!

In [line 5](https://github.com/kea-dpd/Group-Car-Recommendation/blob/4cf3fc102263c9e7a3156019090c97281f65f166/README.md?plain=1#L5)

Consider this instead: 

>Follow [the Teams link](https://teams.microsoft.com/l/channel/19%3anma6VlSbIloU8Xp5YU60zQFELuY_tSWoMHfOA6xe90I1%40thread.tacv2/Generel?groupId=10a85a51-aa87-4051-955f-af4887b00183&tenantId=d10c3c6e-c228-4944-8b6a-6067c6afe3c9)

```markdown
#yours 
Follow the Teams link: https://teams.microsoft.com/l/channel/19%3anma6VlSbIloU8Xp5YU60zQFELuY_tSWoMHfOA6xe90I1%40thread.tacv2/Generel?groupId=10a85a51-aa87-4051-955f-af4887b00183&tenantId=d10c3c6e-c228-4944-8b6a-6067c6afe3c9

# mine
Follow [the Teams link](https://teams.microsoft.com/l/channel/19%3anma6VlSbIloU8Xp5YU60zQFELuY_tSWoMHfOA6xe90I1%40thread.tacv2/Generel?groupId=10a85a51-aa87-4051-955f-af4887b00183&tenantId=d10c3c6e-c228-4944-8b6a-6067c6afe3c9)
```

Small change - huge impact on readability 🌹
