### ISSUE TITLE
Decide on business model

### ISSUE THREAD

**Issue by EmilBystrup** [kea-dpd/Group-Car-Recommendation#54]

**Comment by jona937d** [comment]
In this section will have a quick run through of how Nyvogn will be able to provide a substantial profit. 

The main source of income in the company will be affiliate marketing / pay per lead, for this we will provide different options for you to choose from. 

But first let’s define what a lead is. A lead is characterized as a direct connection through email, phone, or in-person introduction to a potential customer with an interest in buying a product or service in our case, a referral to the website. The cost associated with generating a lead is accrued irrespective of the eventual outcome of the interaction, setting it apart from the customer acquisition cost, which evaluates the expense of acquiring customers who have completed a purchase.  

Affiliate marketing is widely known in the social media industry, where influencers give away “special deals” for example, 20% off on a beauty product, the customer just must use their code, when they check out for a 20% discount. The20% of the beauty product is then paid to the influencer, and the company keeps the 80%. This is a very successful business model to use with medium or micro influencers. 
But this type of advertising does not make sense for a startup, Nyvogn needs to make a name for itself before this could be a possibility. 

According to 'Lead Locate' the average cost of a lead with a low closing ratio is between $50 and $500. This cost may appear high considering the lower likelihood of conversion. As a result, we suggest exploring the option of a slight price increase, tied to the successful sale closure by the dealership.​ (Lead Locate, 2023)​Et billede, der indeholder tekst, skærmbillede, nummer/tal, Font/skrifttype

Automatisk genereret beskrivelse 



![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/92019351/d1e73885-53b6-4003-b6f5-287002a5f56b)



__Figure 1 CPL = Cost Per Lead__

An alternative approach could involve the car dealership paying a modest fee for each click that directs a customer to their website. While this might be an effective way to introduce a new lead website, it may not be the most lucrative long-term solution. 

Another option might involve entering a partnership with various car dealerships, granting them access to be featured on Nyvogn. However, this may not be the favored choice, as it relies on the end customer's awareness of Nyvogn and the dealerships' willingness to be promoted through the website. 

Furthermore, for a fee, dealerships can promote their cars by having Nyvogn show their cars on top of search results/the car match function. 

The ideal strategy for Nyvogn could involve a combination of the previous three approaches. Nyvogn could establish a system where they receive a modest fee each time a customer is directed to a car dealership's website. Additionally, Nyvogn could explore partnership opportunities, offering dealerships access to be showcased on Nyvogn and the potential to feature on the 'promoted page’. 

### BMC



![Image](https://github.com/kea-dpd/Group-Car-Recommendation/assets/92019351/4e0e2b31-d5ef-4557-8d32-bada1b703352)
