### ISSUE TITLE
Decide customer segment

### ISSUE THREAD

**Issue by haidaransari** [kea-dpd/Group-Car-Recommendation#55]

**Comment by jona937d** [comment]
**Customer segment** 

_MVP customer segment:_ 

Initially focus on curious first-time buyers of a new car, with a fulltime job, looking to start a family or recently became parents. People with minimal car knowledge and insight into the new car market. Potential car buyers that want to know what they can get with their budgets and needs. 

35+ year old females, males and whatever in-between, with a minimum annual income of 450k dkk. Region hovedstaden, region midtjylland, region midtsjælland, region nordjylland.  

_Feature complete customer segment:_ 

35-60+ year olds. People with minimal car knowledge and insight into the new car market. Potential car buyers that want to know what they can get with their budgets and needs. Individuals looking for the best price for their favorite car brand/model.  

Females, males and others, with a minimum annual income of 450k dkk. Region hovedstaden, region midtjylland, region midtsjælland, region nordjylland.
