### ISSUE TITLE
Figure out which questions to ask

### ISSUE THREAD

**Issue by Magnus2605** [kea-dpd/Group-Car-Recommendation#67]
Figure out which questions to ask the users when they are trying to find a new car

**Comment by Magnus2605** [comment]
Please note that the questions should be formed so that it can directly filter the data we have

**Comment by EmilBystrup** [comment]
Question 0 - Use the recommendation tool, does the customer want to use it or just browse the cars. 
Question 1 - Model -  Choose the type of car you're in the market for. Shows different car types (SUV, Hybrid, Stationcar etc.)
Question 2 - Purpose - Select the purpose of the car, is it for city driving, terrian, should it be spacious etc. 
Question 3 - Specification - Choose propellant, minimum emission number and budget. 
Question 4 - Create account - Giving the option to create an account for saving and liking cars
